### ISSUE TITLE
Solving Third Distinct Maximum in an Integer Array

### ISSUE THREAD

**Issue by MrImmortal09** [DSC-IIITL/GitGrind#10]
Hey @shishiro26 @Illuminati9 ,
Please assign-me to solve Problems/Solution/Question_4.md. 
I will try my best. 
(LIT2023002).

**Comment by MrImmortal09** [comment]
Pls assign-me

**Comment by shishiro26** [comment]
We are currently not accepting any assignees. Come back when the event starts.

**Comment by Karanagarwal12** [comment]
@shishiro26 , when will the event start ?

**Comment by MrImmortal09** [comment]
@Illuminati9 Please assign me now

**Comment by PavanaSakethaRam** [comment]
Do follow the Issue template for the Title and the Description and also refer to issue #14
