### ISSUE TITLE
Solving Strictly Increasing Array with One Removal

### ISSUE THREAD

**Issue by 0PrashantYadav0** [DSC-IIITL/GitGrind#12]
Hi @PavanaSakethaRam ,

I'd like to solve the Question_1. I understand that it's about sorting but with special conditions. 

I can take this on. 
I read all the description about it. 

Thanks,
0PrashantYadav0
LCI2025025

**Comment by GaganMishra305** [comment]
Hi @PavanaSakethaRam , i would like to work on this issue. Please assign it to me.

**Comment by saiganeshposhith** [comment]
hi @PavanaSakethaRam  sir,@Illuminati9  sir i would like to work on this issue.please assign it to me.                                                                               
                     ( lci2023032)

**Comment by shishiro26** [comment]
@0PrashantYadav0  Try to add the labels to the issue

**Comment by 0PrashantYadav0** [comment]
Sure @shishiro26

**Comment by 0PrashantYadav0** [comment]
@shishiro26 @Illuminati9  please reassign this assignment to me

**Comment by akhilender-bongirwar** [comment]
@0PrashantYadav0,  refer to issue #26 and ask for assignment for the issue over there.
