### ISSUE TITLE
Provide Solution to Question_4 

### ISSUE THREAD

**Issue by digvijay2406** [DSC-IIITL/GitGrind#14]
Hey @PavanaSakethaRam @Illuminati9 @shishiro26 
I wish to solve the Question_4.md. Please assign it to me.

**Comment by GaganMishra305** [comment]
Hey @PavanaSakethaRam . I would like to work on this issue. Please assign this to me.

**Comment by Karanagarwal12** [comment]
Hey @PavanaSakethaRam  @Illuminati9 @shishiro26 @akhilender-bongirwar ,
I would like to contribute on this repo by solving this issue, please assign this issue to me.

**Comment by Karanagarwal12** [comment]
Hey @PavanaSakethaRam  @Illuminati9 @shishiro26 @akhilender-bongirwar ,
I would like to contribute on this repo by solving this issue, please assign this issue to me.

**Comment by PavanaSakethaRam** [comment]
@beforeIkillYou @Karanagarwal12 The Issue has already been assigned. Come back when there is a opportunity to work on this issue or feel free to create your own issues

**Comment by Karanagarwal12** [comment]
@PavanaSakethaRam ,
I have two different approaches for this problem, if the one who is assigned posts one of them can I post the second one?

**Comment by PavanaSakethaRam** [comment]
@digvijay2406 Do follow the Issue Template for Issue Title and the Issue Description while creating the Issues.
