### ISSUE TITLE
Solving findNumber in Alternate Approach portion.

### ISSUE THREAD

**Issue by GaganMishra305** [DSC-IIITL/GitGrind#15]
Hey @PavanaSakethaRam @Illuminati9  I would like to work on this issue. Please assign it to me.

**Comment by beforeIkillYou** [comment]
Hey @PavanaSakethaRam , I would like to work on this issue. Please assign it to me.

**Comment by Illuminati9** [comment]
Hey @beforeIkillYou , can you mention the question. So that I can assign the issue to you.
