### ISSUE TITLE
Fix Bugs in Missing_Numbers Problem

### ISSUE THREAD

**Issue by akhilender-bongirwar** [DSC-IIITL/GitGrind#16]
- Navigate to Problems/Fix_Bugs.
- There you can find the Missing_Numbers.cpp file.
- It has some logical errors and your task is to solve them.

**Comment by GaganMishra305** [comment]
Hey @akhilender-bongirwar , i would like to work on this issue. Please assign it to me.

**Comment by akhilender-bongirwar** [comment]
Go on @beforeIkillYou 🚀

**Comment by AMANVISHWAKARMA27** [comment]
hey @akhilender-bongirwar i would like to work on this issue.
