### ISSUE TITLE
Fix Bugs in Next_Element Problem

### ISSUE THREAD

**Issue by akhilender-bongirwar** [DSC-IIITL/GitGrind#17]
- Navigate to Problems/Fix_Bugs.
- There you can find the Next_Element.cpp file.
- It has some logical errors and your task is to solve them.

**Comment by AMANVISHWAKARMA27** [comment]
hey @akhilender-bongirwar i would like to work on this  issue . Kindly assign me this.

**Comment by 0PrashantYadav0** [comment]
Hii @akhilender-bongirwar 
I would like to work on this issue. Please assign this to me.

**Comment by aryamagarwal** [comment]
Hey @akhilender-bongirwar . Kindly assign this issue to me, I want to work on it.

**Comment by akhilender-bongirwar** [comment]
Assigning in chronological order. @AMANVISHWAKARMA27 go on 🚀

**Comment by shishiro26** [comment]
Go on @0PrashantYadav0 🚀.

**Comment by 0PrashantYadav0** [comment]
hye @shishiro26  I already created a pull request 18 hours ago. So please do check that asap.
