### ISSUE TITLE
Fix Bugs in Paired_Char Problem

### ISSUE THREAD

**Issue by akhilender-bongirwar** [DSC-IIITL/GitGrind#18]
### Description:
- Navigate to Problems/Fix_Bugs.
- There you can find the Paired_Char.cpp file.
- It has some logical errors and your task is to solve them.

**Note:**

- Please make sure to follow the guidelines mentioned in the README file.
- Commit your changes frequently and use descriptive commit messages.
- If you have any doubts or need clarifications, reach out on the [GDSC IIITL Discord Server](https://discord.gg/NUdeuTy33Z).

Happy coding! 🚀

**Comment by Priyanshu-2005** [comment]
hey @akhilender-bongirwar  i want to fix bug of this problem Kindly assign me the problem.

**Comment by 0PrashantYadav0** [comment]
Hye @akhilender-bongirwar 
Please assign this to me as I would like to solve tha bug.

**Comment by Prtm2110** [comment]
@akhilender-bongirwar I can fix the bug please assign it to me

**Comment by akhilender-bongirwar** [comment]
Go on @Priyanshu-2005 🚀.
