### ISSUE TITLE
Fix Bugs in Register_Username Problem

### ISSUE THREAD

**Issue by akhilender-bongirwar** [DSC-IIITL/GitGrind#19]
### Description:

- Navigate to Problems/Fix_Bugs.
- There you can find the Register_Username.cpp file.
- It has some logical errors and your task is to solve them.

**Note:**

- Please make sure to follow the guidelines mentioned in the README file.
- Commit your changes frequently and use descriptive commit messages.
- If you have any doubts or need clarifications, reach out on the [GDSC IIITL Discord Server](https://discord.gg/NUdeuTy33Z).

Happy coding! 🚀

**Comment by AMANVISHWAKARMA27** [comment]
hey @akhilender-bongirwar i want to contribute in this issue by fixing bugs. Kindly assign me the problem.

**Comment by Illuminati9** [comment]
Go on @AMANVISHWAKARMA27 🚀

**Comment by shishiro26** [comment]
@AMANVISHWAKARMA27, it has been more than 12 hours since we received an update from your side. We are unassigning you, and this issue is now available for someone else to take.

**Comment by gauravghodinde** [comment]
hey @akhilender-bongirwar  I want to contribute to this issue. Kindly assign me the problem.

**Comment by saiganeshposhith** [comment]
hi sir @Illuminati9 @shishiro26 @PavanaSakethaRam ,i can do this problem,please assign it to me

**Comment by 0PrashantYadav0** [comment]
I would like to work on this so please assign this to me

**Comment by akhilender-bongirwar** [comment]
Go on @gauravghodinde
