### ISSUE TITLE
to solve the Question_2.md

### ISSUE THREAD

**Issue by saiganeshposhith** [DSC-IIITL/GitGrind#20]
### Description:

[Provide a detailed description of the issue. Include the problem statement, relevant code snippets (if applicable), and any additional context necessary for understanding the problem.]

### Proposed Changes:

[Describe the changes you plan to make to address the issue. If you're providing a solution, include the code snippets or algorithm you intend to implement. For bug fixes, explain the changes you will make to resolve the bug.]

### Additional Information (if any):

[Include any additional information that might be helpful in understanding the issue, such as environment details, related issues, etc.]

---

**Note:**

- Please make sure to follow the guidelines mentioned in the README file.
- Commit your changes frequently and use descriptive commit messages.
- If you have any doubts or need clarifications, reach out on the [GDSC IIITL Discord Server](https://discord.gg/NUdeuTy33Z).

Happy coding! 🚀

**Comment by saiganeshposhith** [comment]
hi @Illuminati9 @PavanaSakethaRam sir  i want to solve this question ,sir please assign to me   lci2023032

**Comment by shishiro26** [comment]
Hello, @saiganeshposhith!

Thank you for your interest in contributing to GitGrind:CP Edition! To ensure smooth collaboration, we kindly request you to follow our issue template while creating new issues. This helps us understand the problem clearly and work towards a solution effectively issue template and add the labels

**Comment by PavanaSakethaRam** [comment]
@saiganeshposhith Do follow the Issue Template for Issue Title and the Issue Description while creating the Issues.
