### ISSUE TITLE
Fix Bugs in Sorting Problem

### ISSUE THREAD

**Issue by akhilender-bongirwar** [DSC-IIITL/GitGrind#21]
### Description:
- Navigate to Problems/Fix_Bugs.
- There you can find the Sorting.cpp file.
- It has some logical errors and your task is to solve them.

**Note:**

- Please make sure to follow the guidelines mentioned in the README file.
- Commit your changes frequently and use descriptive commit messages.
- If you have any doubts or need clarifications, reach out on the [GDSC IIITL Discord Server](https://discord.gg/NUdeuTy33Z).

Happy coding! 🚀

**Comment by gauravghodinde** [comment]
hey @akhilender-bongirwar 
I would like to work on this issue. Please assign this to me.

**Comment by 0PrashantYadav0** [comment]
Hye @akhilender-bongirwar  
please assign this task to me as I would like to fix the bug

**Comment by akhilender-bongirwar** [comment]
Assigning in chronological order.
@gauravghodinde, go on 🚀.

**Comment by shishiro26** [comment]
Thank you for contributing @gauravghodinde
