### ISSUE TITLE
Provide an alternate solution to TOH problem

### ISSUE THREAD

**Issue by shishiro26** [DSC-IIITL/GitGrind#22]
### Description:
 - Navigate to Problems/Alternate_Approach
 - There you can find the TOH.cpp file.
 - Provide an alternate method to solve the problem 
---

**Note:**

- Please make sure to follow the guidelines mentioned in the README file.
- Commit your changes frequently and use descriptive commit messages.
- If you have any doubts or need clarifications, reach out on the [GDSC IIITL Discord Server](https://discord.gg/NUdeuTy33Z).

Happy coding! 🚀

**Comment by Karanagarwal12** [comment]
hey @akhilender-bongirwar @shishiro26 ,
I would like to work on this issue, please assign this to me.

**Comment by akhilender-bongirwar** [comment]
Go on @Karanagarwal12 🚀

**Comment by shishiro26** [comment]
@Karanagarwal12 , it has been more than 12 hours since we received an update from your side. We are unassigning you, and this issue is now available for someone else to take.

**Comment by Karanagarwal12** [comment]
@shishiro26 ,
I have a PR pending which is not merged for a long time for the issue #29 because of that I was not able to make another PR.
I have solved this issue also but just can't do another PR.
Please reassign this to me

**Comment by Karanagarwal12** [comment]
@shishiro26 ,
My previous PR is merged, please reassign this issue to me.

**Comment by PavanaSakethaRam** [comment]
@Karanagarwal12 You have been assigned to the Issue. Solve it ASAP and Raise a PR with a tag to this Issue to close it. Happy Coding!!🚀
