### ISSUE TITLE
Provide an alternate solution to GCD

### ISSUE THREAD

**Issue by shishiro26** [DSC-IIITL/GitGrind#23]
### Description:

- Navigate to Problems/Alternate_Approach
- There you can find the GCD.cpp file.
- Provide an alternate method to solve the problem

**Note:**

- Please make sure to follow the guidelines mentioned in the README file.
- Commit your changes frequently and use descriptive commit messages.
- If you have any doubts or need clarifications, reach out on the [GDSC IIITL Discord Server](https://discord.gg/NUdeuTy33Z).

Happy coding! 🚀

**Comment by Siri-Maya-Lalitha-10** [comment]
Hey @shishiro26 ,
      I would like to work on this issue. Please assign this to me.

**Comment by shishiro26** [comment]
Go on @Siri-Maya-Lalitha-10 🚀

**Comment by blunterdecosta123** [comment]
Hey @shishiro26 I would like to work on this issue. please assign it to me.

**Comment by shishiro26** [comment]
@blunterdecosta123 This issue has already been assigned, so please check other issues
