### ISSUE TITLE
Provide an alternate solution to Palindrome

### ISSUE THREAD

**Issue by shishiro26** [DSC-IIITL/GitGrind#24]
### Description:

 - Navigate to Problems/Alternate_Approach
 - There you can find the palindrome.cpp file.
 - Provide an alternate method to solve the problem
 

**Note:**

- Please make sure to follow the guidelines mentioned in the README file.
- Commit your changes frequently and use descriptive commit messages.
- If you have any doubts or need clarifications, reach out on the [GDSC IIITL Discord Server](https://discord.gg/NUdeuTy33Z).

Happy coding! 🚀

**Comment by saiganeshposhith** [comment]
hi sir @PavanaSakethaRam  @shishiro26 @Illuminati9  i would like to solve this issue ,please assign to me sir  ( lci2023032)

**Comment by shishiro26** [comment]
Go on @saiganeshposhith 🚀

**Comment by ashwinisingh17** [comment]
hii @shishiro26  I would to contribute in this problem . So please assign this to me

**Comment by shishiro26** [comment]
@ashwinisiningh  This issue has already been assigned, so please check other issues

**Comment by blunterdecosta123** [comment]
hii @shishiro26 I would to contribute in this problem . So please assign this to me

**Comment by shishiro26** [comment]
Go on @ashwinisiningh 🚀. Solve it asap
