### ISSUE TITLE
Provide an alternate solution to Power

### ISSUE THREAD

**Issue by shishiro26** [DSC-IIITL/GitGrind#25]
### Description:

- Navigate to Problems/Alternate_Approach
- There you can find the power.cpp file.
- Provide an alternate method to solve the problem

**Note:**

- Please make sure to follow the guidelines mentioned in the README file.
- Commit your changes frequently and use descriptive commit messages.
- If you have any doubts or need clarifications, reach out on the [GDSC IIITL Discord Server](https://discord.gg/NUdeuTy33Z).

Happy coding! 🚀

**Comment by GaganMishra305** [comment]
Hey @akhilender-bongirwar @shishiro26 @Illuminati9 , I would like to do this program with an alternative recursive approach. Please assign this to me.

**Comment by ashwinisingh17** [comment]
Hey @akhilender-bongirwar @shishiro26 @Illuminati9 , I would like to do this program with an alternative approach using pow(). Please assign this to me.

**Comment by shishiro26** [comment]
Go on @beforeIkillYou  🚀

**Comment by blunterdecosta123** [comment]
Hey @akhilender-bongirwar @shishiro26 @Illuminati9 , I would like to do this program with an alternative approach using pow(). Please assign this to me.
