### ISSUE TITLE
Provide an Optimized Solution for Factorial.cpp

### ISSUE THREAD

**Issue by PavanaSakethaRam** [DSC-IIITL/GitGrind#31]
### Description:

- Navigate to Problems/Optimize_solution
- There you can find the `factorial.cpp` file.
- Provide Optimal Solution for the problem in C++

**Note:**

- Please make sure to follow the guidelines mentioned in the README file.
- Commit your changes frequently and use descriptive commit messages.
- If you have any doubts or need clarifications, reach out on the [GDSC IIITL Discord Server](https://discord.gg/NUdeuTy33Z).

Happy coding! 🚀

**Comment by Karanagarwal12** [comment]
Hey @PavanaSakethaRam ,
I would like to solve this issue using the recursive approach, please assign me this issue.

**Comment by PavanaSakethaRam** [comment]
@Karanagarwal12 As you have already been assigned to #29 , complete your work there to work on this issue. Happy Coding!! 🚀

**Comment by MrImmortal09** [comment]
Hey @PavanaSakethaRam ,
I would like to solve this issue.
🙂

**Comment by Karanagarwal12** [comment]
@PavanaSakethaRam 
I have solved the #29 issue and already made a PR, can I work on this issue now ?
Assign me please.

**Comment by Dishant-garg** [comment]
Hey @PavanaSakethaRam ,
I would like to solve this issue, please assign me this issue

**Comment by AMANVISHWAKARMA27** [comment]
hey @PavanaSakethaRam i would like to work on the issue. Kindly assign me this.

**Comment by ashwinisingh17** [comment]
Hey @PavanaSakethaRam ,
I would like to solve this issue using the recursive approach, please assign me this issue.

**Comment by 0PrashantYadav0** [comment]
Hi @PavanaSakethaRam 

Please assign me this project as I would like to work on it.

Thank you.

**Comment by shishiro26** [comment]
Thanks for volunteering gents. Assigning in chronological order!
Go on @MrImmortal09  🚀
