### ISSUE TITLE
Provide an Optimized Solution for Fibonacci.cpp

### ISSUE THREAD

**Issue by PavanaSakethaRam** [DSC-IIITL/GitGrind#32]
### Description:

- Navigate to Problems/Optimize_solution
- There you can find the `fibonacci.cpp` file.
- Provide Optimal Solution for the problem in C++

**Note:**

- Please make sure to follow the guidelines mentioned in the README file.
- Commit your changes frequently and use descriptive commit messages.
- If you have any doubts or need clarifications, reach out on the [GDSC IIITL Discord Server](https://discord.gg/NUdeuTy33Z).

Happy coding! 🚀

**Comment by vishalparida** [comment]
Hello @PavanaSakethaRam, I would like to optimize the code. Please assign it to me.

**Comment by PavanaSakethaRam** [comment]
@vishalparida You have been assigned to the Issue. Solve it ASAP and Raise a PR with a tag to this Issue to close it. Happy Coding!!🚀

**Comment by psg-19** [comment]
hey @PavanaSakethaRam , i wish to optimize the code . please assign me the task

**Comment by PavanaSakethaRam** [comment]
@psg-19 Sice the issue has already been assigned, wait till a PR is raised and then try to provide a more optimized solution than the PR. Happy Coding!!🚀
