### ISSUE TITLE
Provide an Optimized Solution for FindNumber.cpp

### ISSUE THREAD

**Issue by PavanaSakethaRam** [DSC-IIITL/GitGrind#33]
### Description:

- Navigate to Problems/Optimize_solution
- There you can find the `findNumber.cpp` file.
- Provide Optimal Solution for the problem in C++

**Note:**

- Please make sure to follow the guidelines mentioned in the README file.
- Commit your changes frequently and use descriptive commit messages.
- If you have any doubts or need clarifications, reach out on the [GDSC IIITL Discord Server](https://discord.gg/NUdeuTy33Z).

Happy coding! 🚀

**Comment by Dishant-garg** [comment]
hey @PavanaSakethaRam i want to optimize this solution through binary search, please assign me this issue

**Comment by AMANVISHWAKARMA27** [comment]
hey @PavanaSakethaRam i want to provide an optimized solution to this. Please assign me the problem.

**Comment by PavanaSakethaRam** [comment]
@Dishant-garg You have been assigned to the Issue. Solve it ASAP and Raise a PR with a tag to this Issue to close it. Happy Coding!!🚀

**Comment by PavanaSakethaRam** [comment]
@AMANVISHWAKARMA27 Since the Assignee system works on First Come First Serve, the issue has been assigned to someone else. Try to be quick on getting the issue assigned. Happy coding!!🚀

**Comment by Priyanshu-2005** [comment]
hey @PavanaSakethaRam i want to provide an optimized solution to this. Kindly assign me the problem.

**Comment by 0PrashantYadav0** [comment]
Hello @PavanaSakethaRam  i would like to work on this so please assign this to me

**Comment by shibo911** [comment]
Hello @PavanaSakethaRam , I would like to provide an optimised solution, so please assign me this issue. thanks.

**Comment by satyajit1206** [comment]
Hey @PavanaSakethaRam i want to optimize this solution, please assign me this issue.

**Comment by shishiro26** [comment]
Go on @AMANVISHWAKARMA27 🚀.
