### ISSUE TITLE
Provide an Optimized Solution for MinAndMax.cp

### ISSUE THREAD

**Issue by PavanaSakethaRam** [DSC-IIITL/GitGrind#34]
### Description:

- Navigate to Problems/Optimize_solution
- There you can find the `minAndMax.cpp` file.
- Provide Optimal Solution for the problem in C++

**Note:**

- Please make sure to follow the guidelines mentioned in the README file.
- Commit your changes frequently and use descriptive commit messages.
- If you have any doubts or need clarifications, reach out on the [GDSC IIITL Discord Server](https://discord.gg/NUdeuTy33Z).

Happy coding! 🚀

**Comment by digvijay2406** [comment]
Hey @PavanaSakethaRam Please assign me this issue. I have found the solution to this.

**Comment by PavanaSakethaRam** [comment]
@digvijay2406 Since you have unassigned yourself for the Issue #28 , You have been timed out for 9 hrs. Come back after the Timeout.

**Comment by AMANVISHWAKARMA27** [comment]
hey @PavanaSakethaRam kindly assign me the problem, i want to contribute in this

**Comment by PavanaSakethaRam** [comment]
@AMANVISHWAKARMA27 You have been assigned to the Issue. Solve it ASAP and Raise a PR with a tag to this Issue to close it. Happy Coding!!🚀

**Comment by psg-19** [comment]
HEY @PavanaSakethaRam I have made an optimised solution for the problem and like to contribute.

**Comment by PavanaSakethaRam** [comment]
@psg-19 The Issue has already been assigned. Come back when there is a opportunity to work on this issue or feel free to create your own issues.

**Comment by PavanaSakethaRam** [comment]
@AMANVISHWAKARMA27 Since You have already been assigned to #19. Solve the assigned Issue to work on any other Issues.

**Comment by PavanaSakethaRam** [comment]
@psg-19 You have been assigned to the Issue. Solve it ASAP and Raise a PR with a tag to this Issue to close it. Happy Coding!!🚀

**Comment by Priyanshu-2005** [comment]
@PavanaSakethaRam i want to provide an optimized solution for MinAndMax kindly assign me the issue

**Comment by shishiro26** [comment]
Thank you, @psg-19, for contributing
