### ISSUE TITLE
Provide an Optimized Solution for Sorting.cpp

### ISSUE THREAD

**Issue by PavanaSakethaRam** [DSC-IIITL/GitGrind#35]
### Description:

- Navigate to Problems/Optimize_solution
- There you can find the `sorting.cpp` file.
- Provide Optimal Solution for the problem in C++

**Note:**

- Please make sure to follow the guidelines mentioned in the README file.
- Commit your changes frequently and use descriptive commit messages.
- If you have any doubts or need clarifications, reach out on the [GDSC IIITL Discord Server](https://discord.gg/NUdeuTy33Z).

Happy coding! 🚀

**Comment by digvijay2406** [comment]
Hey @PavanaSakethaRam , having completed my 9hrs timeout, I want to work on this issue. Please assign this to me.

**Comment by PavanaSakethaRam** [comment]
@digvijay2406 You have been assigned to the Issue. Solve it ASAP and Raise a PR with a tag to this Issue to close it. Happy Coding!!🚀

**Comment by gauravghodinde** [comment]
hey @PavanaSakethaRam 
I would like to work on this issue. Please assign this to me.

**Comment by saiganeshposhith** [comment]
sir @PavanaSakethaRam @Illuminati9 @shishiro26  please assign it to me i have betteromptimised code for this issue
