### ISSUE TITLE
Provide an alternate solution to Longest Subarray Length

### ISSUE THREAD

**Issue by PavanaSakethaRam** [DSC-IIITL/GitGrind#36]
### Description:

 - Navigate to Problems/Alternate_Approach
 - There you can find the `LongestSubarrayLength.cpp` file.
 - Provide an alternate method to solve the problem
 

**Note:**

- Please make sure to follow the guidelines mentioned in the README file.
- Commit your changes frequently and use descriptive commit messages.
- If you have any doubts or need clarifications, reach out on the [GDSC IIITL Discord Server](https://discord.gg/NUdeuTy33Z).

Happy coding! 🚀

**Comment by Priyanshu-2005** [comment]
hey @PavanaSakethaRam  i want to provide an alternate approach for longest subarray please assign this issue to me

**Comment by PavanaSakethaRam** [comment]
@Priyanshu-2005 You have been assigned to the Issue. Solve it ASAP and Raise a PR with a tag to this Issue to close it. Happy Coding!!🚀

**Comment by AMANVISHWAKARMA27** [comment]
hey @PavanaSakethaRam i want to provide an alternate solution for the longest subarray. Please assign the issue to me.

**Comment by PavanaSakethaRam** [comment]
@AMANVISHWAKARMA27 The Issue has already been assigned. Come back when there is a opportunity to work on this issue or feel free to create your own issues.

**Comment by ashwinisingh17** [comment]
hey @PavanaSakethaRam i would like to provide an alternate solution for this problem . Please assign the issue to me.

**Comment by Aditya2023003** [comment]
hey @PavanaSakethaRam i would like to provide an alternate solution for this problem . Please assign the issue to me.
