### ISSUE TITLE
Provide an alternate approach for Question_4

### ISSUE THREAD

**Issue by Karanagarwal12** [DSC-IIITL/GitGrind#54]
Hey @PavanaSakethaRam @akhilender-bongirwar @shishiro26 @Illuminati9,
I have an alternate or better approach for solving the Question_4, please assign me this issue, I would like to work on it.

**Comment by ashwinisingh17** [comment]
Hey @PavanaSakethaRam @akhilender-bongirwar @shishiro26 @Illuminati9,
I have an alternate or better approach for solving the Question_4, please assign me this issue, I would like to work on it.
