### ISSUE TITLE
Provide an Optimized solution for noOfchars.cpp

### ISSUE THREAD

**Issue by Illuminati9** [DSC-IIITL/GitGrind#62]
### Description:

- Navigate to Problems/Optimize_solution
- There you can find the `noOfchars.cpp` file.
- Provide Optimal Solution for the problem in C++
---

**Note:**

- Please make sure to follow the guidelines mentioned in the README file.
- Commit your changes frequently and use descriptive commit messages.
- If you have any doubts or need clarifications, reach out on the [GDSC IIITL Discord Server](https://discord.gg/NUdeuTy33Z).

Happy coding! 🚀

**Comment by GaganMishra305** [comment]
Hey @Illuminati9 @shishiro26 @akhilender-bongirwar @Kota-Karthik , i would like to work on this issue please assign it to me.

**Comment by Illuminati9** [comment]
hey @beforeIkillYou , Assigned it to you , Complete it fastly as deadline is near
