### ISSUE TITLE
Fix Bugs in the Josephus Problem 

### ISSUE THREAD

**Issue by shishiro26** [DSC-IIITL/GitGrind#63]
### Description:
 - Navigate to Problems/Fix_Bugs.
 - There you can find the Josephus.cpp file.
 - It has some logical errors and your task is to solve them.

**Note:**

- Please make sure to follow the guidelines mentioned in the README file.
- Commit your changes frequently and use descriptive commit messages.
- If you have any doubts or need clarifications, reach out on the [GDSC IIITL Discord Server](https://discord.gg/NUdeuTy33Z).

Happy coding! 🚀

**Comment by 0PrashantYadav0** [comment]
Hye @shishiro26
I would like to work on this. So please assign this to me.

**Comment by Prudhvi-232** [comment]
@shishiro26 i want to work on this problem,so please assign this to me
