### ISSUE TITLE
Provide an Optimized approach for reverseString.cpp

### ISSUE THREAD

**Issue by Illuminati9** [DSC-IIITL/GitGrind#64]
### Description:

Navigate to Problems/Optimize_solution
There you can find the `reverseString.cpp` file.
Provide Optimal Solution for the problem in C++

---

**Note:**

- Please make sure to follow the guidelines mentioned in the README file.
- Commit your changes frequently and use descriptive commit messages.
- If you have any doubts or need clarifications, reach out on the [GDSC IIITL Discord Server](https://discord.gg/NUdeuTy33Z).

Happy coding! 🚀

**Comment by GaganMishra305** [comment]
Hey @Illuminati9 @shishiro26 @akhilender-bongirwar , i would like to work on this issue and enhance the already allotted code. Please assign it to me.

**Comment by GaganMishra305** [comment]
Hey @Illuminati9 @shishiro26 @akhilender-bongirwar , i don't have any pending assignments so please assign this issue to me.

**Comment by 0PrashantYadav0** [comment]
Hye @Illuminati9 i would like to work on this so please assign this to me.

**Comment by Illuminati9** [comment]
Hey @beforeIkillYou and @0PrashantYadav0  , I have already assign an issue to you guys previously. Complete them and come here to get assigned.

Note: You will get assigned if nobody is assigned to this issue

**Comment by kalyanchilamkuri** [comment]
@Illuminati9  i would like to work on this issue

**Comment by Illuminati9** [comment]
Hey @kalyanchilamkuri ,  I have assigned this issue to you. Complete this issue as the deadline is near

**Comment by 0PrashantYadav0** [comment]
Hye  @Illuminati9  i already completed my assigned work so please assign this to me .

**Comment by Prudhvi-232** [comment]
@Illuminati9 i want to work on this issue
