### ISSUE TITLE
Provide an alternate solution for the Josephus 

### ISSUE THREAD

**Issue by shishiro26** [DSC-IIITL/GitGrind#65]
### Description:

 - Navigate to Problems/Alternate_Approach
 - There you can find the Josephus.cpp file.
 - Provide an alternate method to solve the problem

---

**Note:**

- Please make sure to follow the guidelines mentioned in the README file.
- Commit your changes frequently and use descriptive commit messages.
- If you have any doubts or need clarifications, reach out on the [GDSC IIITL Discord Server](https://discord.gg/NUdeuTy33Z).

Happy coding! 🚀

**Comment by GaganMishra305** [comment]
Hey @shishiro26 @Illuminati9 @akhilender-bongirwar @Kota-Karthik , Please allot this issue to me . I would like to provide an alternate solution to this Josephus problem.

**Comment by GaganMishra305** [comment]
Hey @shishiro26 @Illuminati9 @akhilender-bongirwar @Kota-Karthik , I would like to use a recursive approach to solve the problem 

josephus problem diagram
![Screenshot 2023-10-22 172128](https://github.com/DSC-IIITL/GitGrind/assets/70949548/96e72e73-8652-4f1b-bd56-0c777510ef93)

I have done some search on this issue and would love to work on it asap.

**Comment by 0PrashantYadav0** [comment]
Hye @shishiro26 

I would to like to provide a better solution for this so please assign this to me.

**Comment by REVANTH-2-0-0-4** [comment]
@shishiro26  i want to work on this issue

**Comment by Illuminati9** [comment]
Hey @beforeIkillYou & @0PrashantYadav0 , You guys have an issue beforehand. Complete them and come here to get assigned. If you nobody is assigned to this issue beforehand.

**Comment by Illuminati9** [comment]
Hey @REVANTH-2-0-0-4 , I have assigned this issue to you. Complete it as soon as possible as deadline is near.

**Comment by GaganMishra305** [comment]
Hey @Illuminati9 i had already completed my previously allotted issues and then asked for this assignment. Sorry for lack of clarification on my part.

**Comment by Illuminati9** [comment]
@beforeIkillYou , Go ahead I have assigned this issue to you
