### ISSUE TITLE
Implement the "hello world" program

### ISSUE THREAD

**Issue by Illuminati9** [DSC-IIITL/GitGrind#7]
Implement the hello world program in c++.

**Comment by Illuminati9** [comment]
hey @Illuminati9 , 
I would like to contribute on this issue. :)

**Comment by arjunkunwar16** [comment]
hey @Illuminati9 , i would like to contribute on this issue .

**Comment by beforeIkillYou** [comment]
hey @Illuminati9 ,i would like to work on this issue.
